#! /bin/bash

# script for installing BTCPay server 

#connect to SSH
function connect_ssh (){
	ssh_IP=$1
	ssh root@$ssh_IP
}
"$@"

#Download btcpay install files
function dload_BTCpay_install(){
	git clone https://github.com/btcpayserver/btcpayserver-docker
}
"$@"

# install docker-library
function install_dock_lib(){
	apt-get update
	apt-get install libltdl7
}
"$@"


# install docker 
function dockerce_install(){
	wget 'https://download.docker.com/linux/debian/dists/jessie/pool/stable/amd64/docker-ce_18.06.1~ce~3-0~debian_amd64.deb'
	dpkg -i docker-ce_18.06.1~ce~3-0~debian_amd64.deb
}
"$@"

# install btcpay server 
function btcpay_install(){
	. ./btcpay-setup.sh -i
}
"$@"

#run btcpay_server
function run_btcpay(){
	computing_power=$1
	docker update btcpayserver_bitcoind --cpus "$computing_power"
}
"$@"






